<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-ABRF4IV4" ignored="0" name="Add Customer Test" tests="3" failures="3" timestamp="12 May 2021 19:59:09 GMT" time="2.129" errors="0">
  <testcase name="addCust" time="0.619" classname="testcases.AddCustomer">
    <failure type="java.lang.AssertionError" message="Add Customer Failed Intentionally">
      <![CDATA[java.lang.AssertionError: Add Customer Failed Intentionally
at testcases.AddCustomer.addCust(AddCustomer.java:24)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- addCust -->
  <testcase name="addCust" time="0.313" classname="testcases.AddCustomer">
    <failure type="java.lang.AssertionError" message="Add Customer Failed Intentionally">
      <![CDATA[java.lang.AssertionError: Add Customer Failed Intentionally
at testcases.AddCustomer.addCust(AddCustomer.java:24)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- addCust -->
  <testcase name="addCust" time="0.331" classname="testcases.AddCustomer">
    <failure type="java.lang.AssertionError" message="Add Customer Failed Intentionally">
      <![CDATA[java.lang.AssertionError: Add Customer Failed Intentionally
at testcases.AddCustomer.addCust(AddCustomer.java:24)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- addCust -->
</testsuite> <!-- Add Customer Test -->
