<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-ABRF4IV4" failures="3" tests="3" name="Add Customer Test" time="1.324" errors="0" timestamp="12 May 2021 14:26:04 GMT">
  <testcase classname="testcases.AddCustomer" name="addCust" time="0.391">
    <failure type="java.lang.AssertionError" message="Add Customer Failed Intentionally">
      <![CDATA[java.lang.AssertionError: Add Customer Failed Intentionally
at testcases.AddCustomer.addCust(AddCustomer.java:24)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- addCust -->
  <testcase classname="testcases.AddCustomer" name="addCust" time="0.174">
    <failure type="java.lang.AssertionError" message="Add Customer Failed Intentionally">
      <![CDATA[java.lang.AssertionError: Add Customer Failed Intentionally
at testcases.AddCustomer.addCust(AddCustomer.java:24)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- addCust -->
  <testcase classname="testcases.AddCustomer" name="addCust" time="0.159">
    <failure type="java.lang.AssertionError" message="Add Customer Failed Intentionally">
      <![CDATA[java.lang.AssertionError: Add Customer Failed Intentionally
at testcases.AddCustomer.addCust(AddCustomer.java:24)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- addCust -->
</testsuite> <!-- Add Customer Test -->
